#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import cv2

def image_callback(msg):
    bridge = CvBridge()
    try:
        # Convert the ROS Image message to OpenCV2 format
        cv_image = bridge.imgmsg_to_cv2(msg, "bgr8")
    except CvBridgeError as e:
        print(e)
    else:
        # Display the image with OpenCV
        cv2.imshow("Image window", cv_image)
        cv2.waitKey(3)


def main():
    rospy.init_node('image_display_node', anonymous=True)
    image_topic = "/camera/rgb/image_raw"  # Adjust to match the topic from your robot arm in Gazebo
    rospy.Subscriber(image_topic, Image, image_callback)
    rospy.spin()

if __name__ == '__main__':
    main()
